# Generated by Django 4.1.3 on 2022-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD_ur_lico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ul', models.CharField(max_length=50, verbose_name='Имя юр. лица')),
                ('adress_ur', models.TextField(blank=True, null=True, verbose_name='Юр. Адрес')),
                ('adress_post', models.TextField(blank=True, null=True, verbose_name='Почтовый Адрес')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('e_mail', models.EmailField(blank=True, max_length=20, verbose_name='Электронная почта')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='ОКПО')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Юр. Лица',
                'verbose_name_plural': 'Юр. Лица',
                'ordering': ['name_ul'],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('suname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=20, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('telegram', models.CharField(max_length=20, verbose_name='Telegram')),
                ('country', models.CharField(max_length=12, verbose_name='Страна')),
                ('region', models.CharField(max_length=20, verbose_name='Регион')),
                ('city', models.CharField(max_length=12, verbose_name='Город')),
                ('category', models.CharField(max_length=12, verbose_name='Категория')),
                ('organisation', models.CharField(max_length=12, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60, verbose_name='Имя файла')),
                ('material', models.CharField(choices=[('banner_440', 'Баннер 440 гр.'), ('film', 'Пленка'), ('banner_510', 'Баннер 510 гр.'), ('setka', 'Сетка'), ('perfo', 'Перфопленка')], max_length=20, verbose_name='Материал')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('width', models.FloatField(default=0, verbose_name='Ширина')),
                ('length', models.FloatField(default=0, verbose_name='Длина')),
                ('resolution', models.IntegerField(default=0, verbose_name='Разрешение')),
                ('color_model', models.CharField(choices=[('RGB', 'rgb'), ('CMYK', 'cmyk'), ('GREY', 'Greyscale'), ('LAB', 'lab')], max_length=10, verbose_name='Цветовая модель')),
                ('size', models.FloatField(default=0, verbose_name='Размер в Мб')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('path_file', models.ImageField(upload_to='image/%y%m%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Продукт-один файл',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
