# Generated by Django 4.1.3 on 2022-11-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ul', models.CharField(max_length=70, verbose_name='Имя юр. лица')),
                ('adress_ur', models.TextField(blank=True, null=True, verbose_name='Юр. Адрес')),
                ('adress_post', models.TextField(blank=True, null=True, verbose_name='Почтовый Адрес')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('e_mail', models.EmailField(blank=True, max_length=20, verbose_name='Электронная почта')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='ОКПО')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Юр. Лица',
                'verbose_name_plural': 'Юр. Лица',
                'ordering': ['name_ul'],
            },
        ),
        migrations.DeleteModel(
            name='BD_ur_lico',
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0, help_text=' Указывается в см.', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('banner_440', 'Баннер 440 гр.'), ('film', 'Пленка'), ('banner_510', 'Баннер 510 гр.'), ('setka', 'Сетка'), ('perfo', 'Перфопленка')], help_text='Выбирите материал для печати', max_length=20, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0, help_text=' Указывается в см.', verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapps.organisation'),
        ),
    ]
