# Generated by Django 4.1.3 on 2022-11-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_organisation_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
