# Generated by Django 4.1.3 on 2022-11-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_alter_orders_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='organisation',
        ),
    ]
